trigger:
    - main

# pool:
#   vmImage: 'ubuntu-latest'
pool:
    name: "Default" # pool onde está o self-hosted agent
    demands:
        - agent.name -equals mylinuxagent

steps:
    # - task: Maven@4
    #   inputs:
    #       goals: "clean package"

    - task: Maven@4
      inputs:
          mavenPomFile: "pom.xml"
          publishJUnitResults: true
          testResultsFiles: "**/surefire-reports/TEST-*.xml"
          javaHomeOption: "JDKVersion"
          mavenVersionOption: "Default"
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
          containerRegistry: "dockerhubconnection"
          repository: "lets2/quarkus-maven-jvm"
          command: "buildAndPush"
          # Dockerfile: "src/main/docker/Dockerfile.mult"
          Dockerfile: "**/Dockerfile.jvm"
          buildContext: "$(System.DefaultWorkingDirectory)" # define o build context na raiz, mesmo o docker estando em outro lugar
          tags: 'latest'
          # tags: |
          #   latest
          #   $(Build.BuildId)
