trigger:
    - main

pool:
    name: "Default" # pool do agente self-hosted
    demands:
        - agent.name -equals mylinuxagent

steps:
    - task: MavenAuthenticate@0
      displayName: "Authenticate Maven feed"
      inputs:
          artifactsFeeds: "mymavenfeed"
          mavenServiceConnections: "ServConnMavenFeed" #

    - task: Maven@4
      displayName: "Build Maven Package"
      inputs:
          mavenPomFile: "pom.xml"
          goals: "clean package"
          javaHomeOption: "JDKVersion"
          mavenVersionOption: "Default"
          mavenOptions: "-Xmx1024m"
          mavenAuthenticateFeed: true # autenticação integrada

    - script: cat $(Agent.TempDirectory)/settings.xml
      displayName: "Debug settings.xml" # verificar se o settings.xml foi gerado corretamente

    - task: Maven@4
      displayName: "Publish to Maven Feed"
      inputs:
          mavenPomFile: "pom.xml"
          goals: "deploy"
          options: "-DskipTests"
          javaHomeOption: "JDKVersion"
          mavenVersionOption: "Default"
          mavenAuthenticateFeed: true # autenticação integrada


    # - script: ls -l target/
    #   displayName: "Check target directory contents"

    # - task: Maven@4
    #   displayName: "Deploy JAR manually"
    #   condition: succeeded()
    #   inputs:
    #       mavenPomFile: "pom.xml"
    #       goals: "deploy:deploy-file"
    #       options: >
    #           -DgroupId=org.gs
    #           -DartifactId=quarkus-maven
    #           -Dversion=1.0.0-SNAPSHOT
    #           -Dpackaging=jar
    #           -Dfile=target/quarkus-maven-1.0.0-SNAPSHOT.jar
    #           -DrepositoryId=mymavenfeed
    #           -Durl=https://pkgs.dev.azure.com/lets2/AZURE/_packaging/mymavenfeed/maven/v1
    #       javaHomeOption: "JDKVersion"
    #       mavenVersionOption: "Default"
    #       mavenAuthenticateFeed: true
